FROM docker.io/postgres:latest

LABEL Leonardo Viana <leonardoviana00@hotmail.com>

ENV POSTGRES_PASSWORD=keycloak
ENV POSTGRES_DB=keycloak
ENV POSTGRES_USER=keycloak



VOLUME [ "/var/lib/postgresql/data" ]


EXPOSE 5432